::: {.panel-tabset}

##### Description

```{r iter5Plot, fig.align = "center", echo = FALSE, out.width="100%"}
ottrpal::include_slide("https://docs.google.com/presentation/d/1fu-KfdN2ldOXB49o9zdpurFbVvl1bOh8cfQ3vu0szk4/edit?slide=id.g3be338b6b90_0_45#slide=id.g3be338b6b90_0_45")
```

##### R code

```{r}
#| label: iter5R
#| warning: false
#| message: false
#| code-fold: show
#| code-summary: "R code for adjusting the point size, transparency, and color"

to_plot %>%
  ggplot(aes(x = JOY,
             y = DESPAIR,
             color = Chocolate,
             shape = Chocolate
            )
         ) +
  geom_point(size = 3,                             #<7>
             alpha = 0.6                             #<8>
            ) +
  xlim(0, 1) +
  ylim(0, 1) +
  theme_bw() +
  scale_color_manual(values = c("Yes" = "#543210",   #<9>
                                "No" = "#00008B")) + #<9>
  labs(x = "Fraction of respondents who reported JOY",
       y = "Fraction of respondents who reported DESPAIR") +
  theme(text = element_text(size = 14))

```

7. This addition sets the size of the points
8. This addition sets the transparency or opacity of the points so that overlapping points are semi-transparent.
9. This addition manually sets a color scheme using hex codes - brown for chocolate group and dark blue for non-chocolate group

##### Python code

```{python}
#| label: iter5Python
#| warning: false
#| message: false
#| code-fold: show
#| code-summary: "Python code for adjusting the point transparency and color"

just_candy_props['colors'] = np.where(just_candy_props['Chocolate'] == "Yes", "#543210", "#00008B")

mpl.rcParams["font.size"] = 14

plt.style.use('seaborn-v0_8-deep')
fig, ax = plt.subplots()
scatter_choc = ax.scatter(just_candy_props['likeness'][mask_choc],just_candy_props['dislikeness'][mask_choc], c = just_candy_props['colors'][mask_choc], marker = "^", label = "Yes", alpha = 0.6)
scatter_nc = ax.scatter(just_candy_props['likeness'][mask_nc],just_candy_props['dislikeness'][mask_nc], c = just_candy_props['colors'][mask_nc], marker = "o", label = "No", alpha = 0.6)
ax.set_xlim(0,1)
ax.set_ylim(0,1)
ax.minorticks_on()
ax.grid(which='major', linestyle='-', linewidth='0.5', color='grey', alpha=0.7)
ax.grid(which='minor', linestyle=':', linewidth='0.3', color='grey', alpha=0.5)
ax.set_xlabel('Fraction of respondents who reported JOY')
ax.set_ylabel('Fraction of respondents who reported DESPAIR')


ax.legend(title="Chocolate")
plt.show()
plt.close()
```
:::
