::: {.panel-tabset}

##### Description

```{r iter13aPot, fig.align = "center", echo = FALSE, out.width="100%"}
ottrpal::include_slide("https://docs.google.com/presentation/d/1fu-KfdN2ldOXB49o9zdpurFbVvl1bOh8cfQ3vu0szk4/edit?slide=id.g3be338b6b90_0_99#slide=id.g3be338b6b90_0_99")
```

<!--
Maybe don't have the legend inside. Outside might be better/preferred since we have labels/text inside. At least discuss the options like direct labeling/etc.
-->

##### R code

```{r}
#| label: iter13aR
#| warning: false
#| message: false
#| code-fold: show
#| code-summary: "R code for simplifying the legend"

to_plot %>%
  ggplot(aes(x = JOY,
             y = DESPAIR,
             label = label,
             color = Chocolate,
             shape = Chocolate
            )
         ) +
  geom_point(size = 3,
             alpha = 0.6
            ) +
  xlim(0, 1) +
  ylim(1, 0) +
  theme_bw() +
  geom_hline(aes(yintercept=0.5), linetype = 'dashed') +
  geom_vline(aes(xintercept=0.5), linetype = 'dashed') +
  annotate("richtext",
           label = "<span style='color: #CB2C2C;'>High</span> Joy<br>
                    <span style='color: #409AA6;'>Low</span> Despair",
           x = 0.955,
           y = 0.025,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #CB2C2C;'>High</span> Joy<br>
                    <span style='color: #CB2C2C;'>High</span> Despair",
           x = 0.955,
           y = 0.975,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #409AA6;'>Low</span> Joy<br>
                    <span style='color: #CB2C2C;'>High</span> Despair",
           x = 0.045,
           y = 0.975,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #409AA6;'>Low</span> Joy<br>
                    <span style='color: #409AA6;'>Low</span> Despair",
           x = 0.045,
           y = 0.025,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  scale_color_manual(values = c("Yes" = "#543210",
                                "No" = "#00008B"),
                     labels = c("Not chocolate",                          #<40>
                                "Chocolate")) +                           #<40>
  geom_text_repel(show.legend = FALSE, max.overlaps = 16) +
  labs(x = "Fraction Joy",                                                #<41>
       y = "Fraction Despair",                                            #<41>
       title = "<b><span style='color: #543210 font-size: 30pt;'>Chocolate</span> is among the most liked candies in 2017</b>",  #<43>
       color = "") +                                                      #<42>
  theme(text = element_text(size = 22),                                   #<43>
        plot.title = element_markdown(hjust = 0.5)) +
  coord_fixed(ratio = 1)

```

40. Setting the display labels in the legend
41. Simplifying the axis labels
42. Turning off the legend title
43. Increasing the text size

##### Python code

```{python}
#| label: iter13aPython
#| warning: false
#| message: false
#| code-fold: show
#| code-summary: "Python code for simplifying the legend"

mpl.rcParams["font.size"] = 14

plt.style.use('seaborn-v0_8-deep')
fig, ax = plt.subplots()
ax.axhline(y=0.5, linestyle = 'dashed', color = 'black')
ax.axvline(x=0.5, linestyle = 'dashed', color = 'black')
scatter_nc = ax.scatter(just_candy_props['likeness'][mask_nc],just_candy_props['dislikeness'][mask_nc], c = just_candy_props['colors'][mask_nc], marker = "o", label = "Not chocolate", alpha = 0.6)
scatter_choc = ax.scatter(just_candy_props['likeness'][mask_choc],just_candy_props['dislikeness'][mask_choc], c = just_candy_props['colors'][mask_choc], marker = "^", label = "Chocolate", alpha = 0.6)
ax.set_xlim(0,1)
ax.set_ylim(1,0)
fig.canvas.draw()
ax_text(x = 0.88, y = 0.1,
        s='<High> Joy\n<Low> Despair',
        highlight_textprops=[{"color": '#CB2C2C'},
                             {"color": '#409AA6'}],
        fontsize = 10,
        ha = 'center',
        va = 'center',
        textalign = 'center',
        ax = ax)


ax_text(x = 0.88, y = 0.875,
        s = '<High> Joy\n<High> Despair',
        highlight_textprops=[{"color": '#CB2C2C'},
                             {"color": '#CB2C2C'}],
        fontsize = 10,
        ha = 'center',
        va = 'center',
        textalign = 'center',
        ax = ax)

ax_text(x = 0.125,  y = 0.875,
        s = '<Low> Joy\n<High> Despair',
        highlight_textprops=[{"color": '#409AA6'},
                             {"color": '#CB2C2C'}],
        fontsize = 10,
        ha = 'center',
        va = 'center',
        textalign = 'center',
        ax = ax)

ax_text(x = 0.125, y = 0.1,
        s = '<Low> Joy\n<Low> Despair',
        highlight_textprops=[{"color": '#409AA6'},
                             {"color": '#409AA6'}],
        fontsize = 10,
        ha = 'center',
        va = 'center',
        textalign = 'center',
        ax = ax)
ax.minorticks_on()
ax.grid(which='major', linestyle='-', linewidth='0.5', color='grey', alpha=0.7)
ax.grid(which='minor', linestyle=':', linewidth='0.3', color='grey', alpha=0.5)
ax.set_xlabel('Fraction Joy')
ax.set_ylabel('Fraction Despair')
fig_text(x = 0.5, y = 0.9,
        s = '<Chocolate> is among the most liked candies in 2017',
        highlight_textprops = [{"color": "#543210", "weight": "bold"}],
        textalign = 'center',
        ha = 'center',
        va = 'bottom',
        fontsize = 15)
texts = [plt.text(just_candy_props['likeness'].iloc[i],
                  just_candy_props['dislikeness'].iloc[i],
                  just_candy_props['label'].iloc[i],
                  fontsize = 6)
          for i in range(len(just_candy_props))]
adjust_text(texts,
  avoid_points = True)
ax.legend(bbox_to_anchor = (1.05, 0.5), title="", loc = "center left")
ax.set_aspect('equal')
plt.tight_layout()
plt.show()
plt.close()

```

:::

::: {.panel-tabset}

##### Description

```{r iter13bPlot, fig.align = "center", echo = FALSE, out.width="100%"}
ottrpal::include_slide("https://docs.google.com/presentation/d/1fu-KfdN2ldOXB49o9zdpurFbVvl1bOh8cfQ3vu0szk4/edit?slide=id.g3c26f54f9da_0_8#slide=id.g3c26f54f9da_0_8")
```

##### R code

```{r}
#| label: iter13bR
#| warning: false
#| message: false
#| code-fold: show
#| code-summary: "R code for simplifying the legend"

to_plot %>%
  ggplot(aes(x = JOY,
             y = DESPAIR,
             label = label,
             color = Chocolate,
             shape = Chocolate
            )
         ) +
  geom_point(size = 3,
             alpha = 0.6
            ) +
  xlim(0, 1) +
  ylim(1, 0) +
  theme_bw() +
  geom_hline(aes(yintercept=0.5), linetype = 'dashed') +
  geom_vline(aes(xintercept=0.5), linetype = 'dashed') +
  annotate("richtext",
           label = "<span style='color: #CB2C2C;'>High</span> Joy<br>
                    <span style='color: #409AA6;'>Low</span> Despair",
           x = 0.955,
           y = 0.025,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #CB2C2C;'>High</span> Joy<br>
                    <span style='color: #CB2C2C;'>High</span> Despair",
           x = 0.955,
           y = 0.975,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #409AA6;'>Low</span> Joy<br>
                    <span style='color: #CB2C2C;'>High</span> Despair",
           x = 0.045,
           y = 0.975,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  annotate("richtext",
           label = "<span style='color: #409AA6;'>Low</span> Joy<br>
                    <span style='color: #409AA6;'>Low</span> Despair",
           x = 0.045,
           y = 0.025,
           fill = NA,
           label.color = NA,
           label.padding = grid::unit(rep(0, 4), "pt")
          ) +
  scale_color_manual(values = c("Yes" = "#543210",
                                "No" = "#00008B"),
                     labels = c("Not chocolate",
                                "Chocolate")) +
  scale_shape_discrete(labels = c("Not chocolate",                        #<44>
                                  "Chocolate")) +                         #<44>
  geom_text_repel(show.legend = FALSE, max.overlaps = 16) +
  labs(x = "Fraction Joy",
       y = "Fraction Despair",
       title = "<b><span style='color: #543210 font-size: 30pt;'>Chocolate</span> is among the most liked candies in 2017</b>",
       color = "",
       shape = "") +                                                      #<45>
  theme(text = element_text(size = 22),
        plot.title = element_markdown(hjust = 0.5)) +
  coord_fixed(ratio = 1)

```

44. Change the labels in the legend for shape too
45. Turn off the legend title for shape too

:::
