
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://www.ottrproject.org/more_features.html#giving-credits-to-contributors).

&nbsp;
&nbsp;
***In [memory](https://galaxyproject.org/jxtx/) of [James Taylor](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02016-0), who was instrumental in initiating this project.***

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Kate Isaac]|
|Content Contributor ([Appendix section about Xena Browser ](https://hutchdatascience.org/DataViz_Considerations/appendix_itcr.html#ucsc-xena-browser)) | [Mary Goldman](https://www.linkedin.com/in/mary-goldman-0a6983122/)|
|Content Director(s) | [Carrie Wright]|
|Content Consultant | [Ted Laderas] - [Elements of Data Visualization](https://hutchdatascience.org/DataViz_Considerations/03_data.html) |
|Acknowledgments| David Miller gave valuable suggestions about content to include |
|**Production**||
|Content Publisher(s)|[Kate Isaac], [Carrie Wright]|
|Content Publishing Reviewer(s)|[Carrie Wright]|
|**Technical**||
|Course Publishing Engineer(s)| Helped with the code for the technical aspects related to the specific course generation|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright], [Ava Hoffman]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Ava Hoffman], [Candace Savonen]|
|Package Developers ([ottrpal]) | [Candace Savonen], [John Muschelli], [Carrie Wright], [Ava Hoffman], [Kate Isaac], [Adam Coffman]|
|**Art and Design**||
|Illustrator(s)| [Kate Isaac], [Carrie Wright]|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| [Allison Peters](https://www.linkedin.com/in/allisonrpeters/), [Maleah O'Connor](https://www.linkedin.com/in/maleah-o-connor/)|


&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Ava Hoffman]: https://www.avahoffman.com/
[Howard Baek]: https://www.linkedin.com/in/howard-baik/
[Kate Isaac]: https://kweav.github.io/
[Katherine Cox]: https://katherinecox.github.io/
[Adam Coffman]:https://www.linkedin.com/in/adamcoffman
[David Miller]: https://www.cancer.gov/about-nci/organization/dcb/about/contact/david-miller
[Ted Laderas]: https://laderast.github.io/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal

